import Navbar from "@/components/shared/navbar";
import "./globals.css";

export const metadata = {
  title: "LWS Kitchen - Food Blog and Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Inter:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`bg-white antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
